### PR TITLE
Async support feature

### PR DESCRIPTION
**Pull request by Ephraim-Akolo**
- Added support for asynchronous requests using httpx, along with tests and examples

### CODE REVIEW

**Comment by jake-ephraim** [comment]
All async test cases passed. All async live tests have now passed.

**Comment by 2pd** [comment]
Thank you for the contribution, we will review and test before merging to next release.

**Comment by jake-ephraim** [comment]
Alright.

**Comment by 2pd** [comment]
We are still investigating the best way to support async, we wish to explore an implementation that could reuse code as muc as possible. 

One concern here could be the new package `httpx` , it should be necessary to wait until it has a stable version.

**Comment by jake-ephraim** [comment]
Okay.
But the implementation is only a mirror of the current requests version, with only little modifications, substituting `requests` for `httpx`.

Is the reuse of code implementation only for the async support?

**Comment by jake-ephraim** [comment]
Why not serve this implementation while working on a better implementation? Half bread is better than none right?

**Pull request closed without merging**
